#!/bin/bash

# apt update
apt-get update 
apt-get install -y --force-yes  iperf inetutils-traceroute tcpdump curl hping3 apache2-utils ettercap-text-only

#clean
apt-get -y autoremove 
apt-get -y clean 
rm -rf /root/.cache
