#!/bin/bash

# apt update
apt-get update 
apt-get install -y --force-yes net-tools inetutils-traceroute tcpdump curl wget
wget https://nexus.opendaylight.org/content/repositories/public/org/opendaylight/integration/opendaylight/0.9.2/opendaylight-0.9.2.tar.gz
tar -xvzf opendaylight-0.9.2.tar.gz
rm opendaylight-0.9.2.tar.gz 
rm -rf /var/cache/apk/*

#clean
apt-get -y autoremove 
apt-get -y clean 
rm -rf /root/.cache
